# Generated by Django 2.2 on 2021-04-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('epic_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('prov_fname', models.CharField(max_length=50)),
                ('prov_midinital', models.CharField(max_length=1)),
                ('prov_lname', models.CharField(max_length=100)),
                ('prov_division', models.CharField(max_length=200)),
                ('prov_department', models.CharField(choices=[('PEDIATRICS', 'PEDIATRICS'), ('SURGERY', 'SURGERY'), ('PRIMARY CARE', 'PRIMARY CARE')], default='PEDIATRICS', max_length=200)),
                ('prov_email', models.EmailField(max_length=254)),
                ('prov_hospital', models.CharField(max_length=200)),
            ],
        ),
    ]
