# Generated by Django 2.2 on 2021-04-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_choice', models.CharField(choices=[('MAIN CAMPUS', 'MAIN CAMPUS'), ('SATELLITE 1', 'SATELLITE 1'), ('SATELLITE 2', 'SATELLITE 2'), ('SATELLITE 3', 'SATELLITE 3')], default='MAIN CAMPUS', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_app.Provider')),
            ],
        ),
    ]
