# Generated by Django 2.2 on 2021-04-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_app', '0002_buildingchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('MAIN CAMPUS', 'MAIN CAMPUS'), ('SATELLITE 1', 'SATELLITE 1'), ('SATELLITE 2', 'SATELLITE 2'), ('SATELLITE 3', 'SATELLITE 3')], default='MAIN CAMPUS', max_length=50)),
                ('floor', models.CharField(choices=[('FLOOR 1', 'FLOOR 1'), ('FLOOR 2', 'FLOOR 2'), ('FLOOR 3', 'FLOOR 3')], default='FLOOR 1', max_length=50)),
                ('room', models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], default='ROOM 1', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='BuildingChoice',
        ),
    ]
