# Generated by Django 2.2 on 2021-04-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_app', '0003_auto_20210408_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_app.Building')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_app.Provider')),
            ],
        ),
    ]
